### ISSUE TITLE
Desenvolver os testes

### ISSUE THREAD

**Issue by ericcarlotto** [ericcarlotto/t1_testeUnidade#1]
- [x] Desenvolver o primeiro teste

- [x] Desenvolver o segundo teste

- [x] Desenvolver o terceiro teste

**Comment by ericcarlotto** [comment]
I finished my part.

**Comment by henriquewwf** [comment]
Teste 1:
![screenshot_eric](https://user-images.githubusercontent.com/61994998/162854483-c3c3e093-3708-4ad8-92c8-f443b6d6fdbf.png)
Teste 2:
![screenshot_henrique](https://user-images.githubusercontent.com/61994998/162854510-2bf40a9e-07da-48b2-8c86-a8c1f5d54c3f.png)
Teste 3: 
![Screenshot 2022-04-11 at 21-27-03 ericcarlotto_t1_testeUnidade Repositório para desenvolver o primeiro trabalho da matéria de qualidade de produto](https://user-images.githubusercontent.com/61994998/162854530-ed0711fa-f959-4d81-842f-f4e0f60c1cfe.png)
